name: Build and publish Docker image

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency: production

jobs:
  publish:
    name: Build and publish Docker image to GitHub Packages
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Auth GitHub
        id: auth
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        id: version
        uses: reecetech/version-increment@2024.10.1
        with:
          scheme: conventional_commits
          increment: patch
          release_branch: main
          use_api: true

      - name: Add tags and labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
          flavor: latest=auto

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64

      - name: Set up Docker Build
        id: build
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}"
          labels: ${{ steps.meta.outputs.labels }}
